[package]
name = "augurs-core"
version.workspace = true
authors.workspace = true
documentation.workspace = true
license.workspace = true
edition.workspace = true
keywords.workspace = true

[dependencies]
serde = { version = "1.0.166", optional = true, features = ["derive"] }
