[package]
name = "outlier"
license.workspace = true
authors.workspace = true
documentation.workspace = true
repository.workspace = true
version.workspace = true
edition.workspace = true
keywords.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
augurs-outlier = { workspace = true, features = ["serde"] }
getrandom = { version = "0.3" }
wit-bindgen.workspace = true
wit-component.workspace = true

[lints]
workspace = true

[package.metadata.component]
package = "augurs:outlier"
