# Build augurs-js with the nightly toolchain and wasm32-unknown-unknown target.
# This is required for the `wasm-bindgen-rayon` dependency, which requires
# some nightly-only features (see .cargo/config.toml).
[toolchain]
channel = "nightly-2024-09-01"
components = ["rust-src"]
targets = ["wasm32-unknown-unknown"]
profile = "minimal"
