serve:
    mdbook serve

build:
    mdbook build

test:
    python3 scripts/test_examples.py



# Install mdbook-langtabs preprocessor
install-langtabs:
    cargo install mdbook-langtabs
    mdbook-langtabs install .
