name: augurs-js

on:
  push:
    branches: ["main"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  test:
    name: JS tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - uses: taiki-e/install-action@921a4027af787cda265c4f334a0f7f89b21d72e9 # v2.75.8
        with:
          tool: just,wasm-pack

      - name: Build augurs-js
        run: just build-augurs-js

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: js/.node-version
      - name: Install dependencies
        run: npm ci
        working-directory: js/testpkg
      - name: Run typecheck
        run: npm run typecheck
        working-directory: js/testpkg
      - name: Run tests
        run: npm run test:ci
        working-directory: js/testpkg
