name: augurs-js

on:
  push:
    branches: ["main"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  test:
    name: JS tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@2c7215f132e9ebf062739d9130488b56d53c060c
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - uses: taiki-e/install-action@07b4745e0c39a41822af610387492e3e53aa222b # v2.83.4
        with:
          tool: just,wasm-pack

      - name: Build augurs-js
        run: just build-augurs-js

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: js/.node-version
      - name: Install dependencies
        run: npm ci
        working-directory: js/testpkg
      - name: Run typecheck
        run: npm run typecheck
        working-directory: js/testpkg
      - name: Run tests
        run: npm run test:ci
        working-directory: js/testpkg
