name: Release-plz

permissions: {}

on:
  push:
    branches:
      - main

jobs:
  # Release unpublished packages.
  release-plz-release:
    name: Release-plz release
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'grafana' }}
    permissions:
      # Required to get secrets from Vault.
      id-token: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@67ef31d5b988238dd797d409d6f9574278e20537
        with:
          toolchain: stable

      - id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@e46fe1e9a2bf9e618bcf8d8d32f3a7381b45c06d # get-vault-secrets/v2.0.0
        with:
          # Secrets placed in the ci/repo/grafana/augurs/<path> path in Vault
          repo_secrets: |
            CARGO_REGISTRY_TOKEN=crates-io:api-token
            GITHUB_TOKEN=github:token

      - name: Run release-plz
        uses: release-plz/action@e8792575c7f2366cf6ff3ccc33ead9ace5b691c7 # v0.5.130
        with:
          command: release

  # Create a PR with the new versions and changelog, preparing the next release.
  release-plz-pr:
    name: Release-plz PR
    runs-on: ubuntu-latest
    permissions:
      # Required to get secrets from Vault.
      id-token: write
      contents: write
      pull-requests: write
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@67ef31d5b988238dd797d409d6f9574278e20537
        with:
          toolchain: stable

      - id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@e46fe1e9a2bf9e618bcf8d8d32f3a7381b45c06d # get-vault-secrets/v2.0.0
        with:
          # Secrets placed in the ci/repo/grafana/augurs/<path> path in Vault
          repo_secrets: |
            CARGO_REGISTRY_TOKEN=crates-io:api-token
            GITHUB_TOKEN=github:token

      - name: Run release-plz
        uses: release-plz/action@e8792575c7f2366cf6ff3ccc33ead9ace5b691c7 # v0.5.130
        with:
          command: release-pr
