name: Track Benchmarks with Bencher

on:
  workflow_run:
    workflows: [Run and Cache Benchmarks]
    types: [completed]

jobs:
  track_benchmarks:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    env:
      BENCHER_PROJECT: augurs
      BENCHER_TESTBED: ubuntu-latest
      PR_BENCHMARK_RESULTS: pr.txt
      BASE_BENCHMARK_RESULTS: base.txt
      GITHUB_EVENT: event.json
      UPPER_BOUNDARY: 0.95
    steps:
      - name: Download Benchmark Results
        uses: actions/github-script@v7
        with:
          script: |
            async function downloadArtifact(artifactName) {
              let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: context.payload.workflow_run.id,
              });
              let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
                return artifact.name == artifactName
              })[0];
              if (!matchArtifact) {
                core.setFailed(`Failed to find artifact: ${artifactName}`);
              }
              let download = await github.rest.actions.downloadArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: matchArtifact.id,
                archive_format: 'zip',
              });
              let fs = require('fs');
              fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/${artifactName}.zip`, Buffer.from(download.data));
            }
            await downloadArtifact(process.env.PR_BENCHMARK_RESULTS);
            await downloadArtifact(process.env.BASE_BENCHMARK_RESULTS);
            await downloadArtifact(process.env.GITHUB_EVENT);
      - name: Unzip Benchmark Results
        run: |
          unzip $PR_BENCHMARK_RESULTS.zip
          unzip $BASE_BENCHMARK_RESULTS.zip
          unzip $GITHUB_EVENT.zip
      - name: Export PR Event Data
        uses: actions/github-script@v7
        with:
          script: |
            let fs = require('fs');
            let prEvent = JSON.parse(fs.readFileSync(process.env.GITHUB_EVENT, {encoding: 'utf8'}));
            core.exportVariable("PR_HEAD", `${prEvent.number}/merge`);
            core.exportVariable("PR_BASE", prEvent.pull_request.base.ref);
            core.exportVariable("PR_BASE_SHA", prEvent.pull_request.base.sha);
            core.exportVariable("PR_NUMBER", prEvent.number);
      - uses: bencherdev/bencher@main

      - name: Track base Benchmarks
        run: |
          bencher run \
          --token "${{ secrets.BENCHER_API_TOKEN }}" \
          --if-branch '${{ env.PR_HEAD }}' \
          --else-branch \
          --file "$BASE_BENCHMARK_RESULTS"
      - name: Create PR threshold
        run: |
          bencher threshold create \
          --project "$BENCHER_PROJECT" \
          --branch '${{ env.PR_HEAD }}' \
          --testbed "$BENCHER_TESTBED" \
          --token "${{ secrets.BENCHER_API_TOKEN }}" \
          --measure latency \
          --test t \
          --upper-boundary ${{ env.UPPER_BOUNDARY }} ||
          true
      - name: Track PR Benchmarks
        run: |
          bencher run \
          --branch '${{ env.PR_HEAD }}' \
          --token "${{ secrets.BENCHER_API_TOKEN }}" \
          --ci-id '${{ env.PR_ID }}' \
          --ci-number '${{ env.PR_NUMBER }}' \
          --github-actions "${{ secrets.GITHUB_TOKEN }}" \
          --err \
          --file "$PR_BENCHMARK_RESULTS"
