name: build-prophet-wasmstan

on:
  push:
    branches: ["main"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  build:
    name: Prophet WASMStan component
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@2c7215f132e9ebf062739d9130488b56d53c060c
        with:
          toolchain: stable
      - uses: taiki-e/install-action@6a1bd70eaac3c8bdf093356838d7ee09fda951cf # v2.85.5
        with:
          tool: cargo-binstall,just,ripgrep,wasmtime
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install deps
        run: just components/install-deps
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      - name: Run node test
        run: just components/test
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: prophet-wasmstan.wasm
          path: components/cpp/prophet-wasmstan/prophet-wasmstan.wasm
      - name: Copy prophet-wasmstan.wasm to augurs
        run: just copy-component-wasm
      - name: Ensure no diffs
        run: git diff --exit-code -- crates/augurs-prophet/prophet-wasmstan.wasm
